/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TURN = 4;
  /** RegularExpression Id. */
  int MOVE = 5;
  /** RegularExpression Id. */
  int FACE = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int DEF = 9;
  /** RegularExpression Id. */
  int EQUALS = 10;
  /** RegularExpression Id. */
  int MOVEDIR = 11;
  /** RegularExpression Id. */
  int MOVEFACE = 12;
  /** RegularExpression Id. */
  int RUNDIRS = 13;
  /** RegularExpression Id. */
  int SALTAR = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int FACING = 16;
  /** RegularExpression Id. */
  int CANPUT = 17;
  /** RegularExpression Id. */
  int CANPICK = 18;
  /** RegularExpression Id. */
  int CANMOVE = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int REPEAT = 21;
  /** RegularExpression Id. */
  int COMMANDS = 22;
  /** RegularExpression Id. */
  int NORTH = 23;
  /** RegularExpression Id. */
  int SOUTH = 24;
  /** RegularExpression Id. */
  int EAST = 25;
  /** RegularExpression Id. */
  int WEST = 26;
  /** RegularExpression Id. */
  int RIGHT = 27;
  /** RegularExpression Id. */
  int LEFT = 28;
  /** RegularExpression Id. */
  int AROUND = 29;
  /** RegularExpression Id. */
  int T_BALLOONS = 30;
  /** RegularExpression Id. */
  int T_CHIPS = 31;
  /** RegularExpression Id. */
  int NUMERO = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int PALABRA = 34;
  /** RegularExpression Id. */
  int CARACTER = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"turn\"",
    "\"move\"",
    "\"face\"",
    "\"put\"",
    "\"pick\"",
    "\"defvar\"",
    "\"=\"",
    "\"move-dir\"",
    "\"move-face\"",
    "\"run-dirs\"",
    "\"skip\"",
    "\"if\"",
    "\"facing-p\"",
    "\"can-put-p\"",
    "\"can-pick-p\"",
    "\"can-move-p\"",
    "\"not\"",
    "\"repeat\"",
    "<COMMANDS>",
    "\":north\"",
    "\":south\"",
    "\":east\"",
    "\":west\"",
    "\":right\"",
    "\":left\"",
    "\":around\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUMERO>",
    "<DIGIT>",
    "<PALABRA>",
    "<CARACTER>",
    "\"(\"",
    "\":balloons\"",
    "\":chips\"",
    "\":front\"",
    "\":back\"",
    "\" :front\"",
    "\" :right\"",
    "\" :left\"",
    "\" :back\"",
    "\")\"",
    "\"\\n\"",
  };

}
