/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TURN = 4;
  /** RegularExpression Id. */
  int MOVE = 5;
  /** RegularExpression Id. */
  int FACE = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int DEF = 9;
  /** RegularExpression Id. */
  int EQUALS = 10;
  /** RegularExpression Id. */
  int MOVEDIR = 11;
  /** RegularExpression Id. */
  int MOVEFACE = 12;
  /** RegularExpression Id. */
  int RUNDIRS = 13;
  /** RegularExpression Id. */
  int SALTAR = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int T_BALLOONS = 16;
  /** RegularExpression Id. */
  int T_CHIPS = 17;
  /** RegularExpression Id. */
  int NUMERO = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int PALABRA = 20;
  /** RegularExpression Id. */
  int CARACTER = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"turn\"",
    "\"move\"",
    "\"face\"",
    "\"put\"",
    "\"pick\"",
    "\"defvar\"",
    "\"=\"",
    "\"move-dir\"",
    "\"move-face\"",
    "\"run-dirs\"",
    "\"skip\"",
    "\"if\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUMERO>",
    "<DIGIT>",
    "<PALABRA>",
    "<CARACTER>",
    "\"(\"",
    "\":right\"",
    "\":left\"",
    "\":around\"",
    "\":north\"",
    "\":south\"",
    "\":east\"",
    "\":west\"",
    "\":balloons\"",
    "\":chips\"",
    "\":front\"",
    "\":back\"",
    "\" :front\"",
    "\" :right\"",
    "\" :left\"",
    "\" :back\"",
    "\")\"",
    "\"\\n\"",
  };

}
