/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TURN = 4;
  /** RegularExpression Id. */
  int MOVE = 5;
  /** RegularExpression Id. */
  int FACE = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int DEF = 9;
  /** RegularExpression Id. */
  int T_BALLOONS = 10;
  /** RegularExpression Id. */
  int T_CHIPS = 11;
  /** RegularExpression Id. */
  int NUMERO = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"turn\"",
    "\"move\"",
    "\"face\"",
    "\"put\"",
    "\"pick\"",
    "\"defvar\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUMERO>",
    "<DIGIT>",
    "\"(\"",
    "\":right\"",
    "\":north\"",
    "\":south\"",
    "\":east\"",
    "\":west\"",
    "\")\"",
    "\"\\n\"",
    "\",\"",
  };

}
